### ISSUE TITLE
Please enable "make install"

### ISSUE THREAD

**Issue by probonopd** [tmstieff/Woke#2]
I would expect it to install the application into the system, along with a desktop file and icon. Please change your `.pro` file it similar to https://github.com/probonopd/FeedTheMonkey/blob/master/FeedTheMonkey.pro.

**Comment by tmstieff** [comment]
Thanks, I've gone ahead and added a desktop file as well as an install target for make.

**Comment by probonopd** [comment]
The desktop file is missing an icon, `Icon=`. Also, no icon is installed to, e.g., `usr/share/icons/hicolor/256x256/apps/woke.png`. This is needed on Linux to properly show up in the menu.

```
 make INSTALL_ROOT=appdir -j$(nproc) install ; find appdir/
/opt/qt59/bin/qmake -install qinstall /home/travis/build/probonopd/Woke/misc/woke.desktop appdir/usr/share/applications/woke.desktop
/opt/qt59/bin/qmake -install qinstall -exe woke appdir/usr/bin/woke
strip appdir/usr/bin/woke
appdir/
appdir/usr
appdir/usr/share
appdir/usr/share/applications
appdir/usr/share/applications/woke.desktop
appdir/usr/bin
appdir/usr/bin/woke
```
