### ISSUE TITLE
openSUSE run error

### ISSUE THREAD

**Issue by gmg137** [tmstieff/Woke#8]
openSUSE Tumbleweed + GNOME
```
Database: connection ok
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f27bcee85c0 (most recent call first):
```

**Comment by tmstieff** [comment]
I will have to setup a VM to test out, but it's probably a Python version mismatch. The binaries are compiled against Python 3 headers. I will look into packaging a Python distribution with the appimage.

**Comment by tmstieff** [comment]
It is indeed a Python versioning problem. As a work around you can run:

`PYTHONHOME=/usr/lib64/python3.6 PYTHONPATH=/usr/lib64/python3.6 ./Woke.AppImage`

**Comment by gmg137** [comment]
Thank you, I test it.


---- Taylor Stieff 编写 ----


It is indeed a Python versioning problem. As a work around you can run:

PYTHONHOME=/usr/lib64/python3.6 PYTHONPATH=/usr/lib64/python3.6 ./Woke.AppImage

―
